id: P5D123282
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni Prayers & Practices
  language: fr
  description: 'Lotsawa House presents the following texts as part of its Prayers
    to Buddha Śākyamuni Series:'
  volume:
    6879e663d65245dda171cc153a82941e:
      title: Prayer for the Future of the Dharma
      parent: Aspiration Prayers
    5ec85b1e3d69476990c15d0b8103a98b:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Aspiration Prayers
    74bda26cb2464f62b7978b4d3488bee5:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Aspiration Prayers
    60b24385d70b4d7aaadbef9a3d5f67fb:
      title: Verses on the Buddha's Previous Lives
      parent: History
    2a052ff50df14e038df8206d7a5f7fc0:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha's Deeds
    d7e758b31402412aa61c8ef90b51e1da:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha's Deeds
    8a4c8338a59041f3af8acbdd5661550d:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha's Deeds
    680424f468ec441f917e356cfcc47e45:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    34c999f178e34f54a12bd772a14a8ac8:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    4519a97e5f1a41b292efca905a6fe0d4:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    237615ea43c14e7c9e0572bb56355b1b:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Sādhanas
    b54215d38383400dbc24ccfaf55e3f84:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Sādhanas
    47e76ec94ee9467dbafd8bed86d0505f:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
created_at: '2022-03-01T03:05:43.225615'
last_modified_at: '2022-03-01T03:05:43.225617'
